In [23]:
import pandas as pd
df = pd.read_csv('GoogleApps.csv')

In [31]:
# Counting (value_counts)
df['Category'].value_counts()

Category
FAMILY                 1574
GAME                    911
TOOLS                   631
MEDICAL                 318
LIFESTYLE               275
PERSONALIZATION         270
FINANCE                 266
BUSINESS                246
SPORTS                  245
PRODUCTIVITY            234
PHOTOGRAPHY             231
HEALTH_AND_FITNESS      216
COMMUNICATION           206
SHOPPING                176
NEWS_AND_MAGAZINES      162
TRAVEL_AND_LOCAL        159
BOOKS_AND_REFERENCE     142
SOCIAL                  142
VIDEO_PLAYERS           114
EDUCATION               108
MAPS_AND_NAVIGATION      94
FOOD_AND_DRINK           84
ENTERTAINMENT            84
AUTO_AND_VEHICLES        63
LIBRARIES_AND_DEMO       61
ART_AND_DESIGN           58
HOUSE_AND_HOME           56
WEATHER                  51
PARENTING                43
COMICS                   42
EVENTS                   38
BEAUTY                   36
DATING                   16
Name: count, dtype: int64

In [ ]:
# Filtering + counting
df[df['Rating'] > 4.5]['Category'].value_counts()

In [30]:
# Basic Groupby
df.groupby('Category').size()

Category
ART_AND_DESIGN           58
AUTO_AND_VEHICLES        63
BEAUTY                   36
BOOKS_AND_REFERENCE     142
BUSINESS                246
COMICS                   42
COMMUNICATION           206
DATING                   16
EDUCATION               108
ENTERTAINMENT            84
EVENTS                   38
FAMILY                 1574
FINANCE                 266
FOOD_AND_DRINK           84
GAME                    911
HEALTH_AND_FITNESS      216
HOUSE_AND_HOME           56
LIBRARIES_AND_DEMO       61
LIFESTYLE               275
MAPS_AND_NAVIGATION      94
MEDICAL                 318
NEWS_AND_MAGAZINES      162
PARENTING                43
PERSONALIZATION         270
PHOTOGRAPHY             231
PRODUCTIVITY            234
SHOPPING                176
SOCIAL                  142
SPORTS                  245
TOOLS                   631
TRAVEL_AND_LOCAL        159
VIDEO_PLAYERS           114
WEATHER                  51
dtype: int64

In [35]:
df.groupby('Type')['Rating'].mean()

Type
Free    4.171955
Paid    4.247957
Name: Rating, dtype: float64

In [38]:
# Multi Insight from 1 group (Aggregation)
df.groupby('Type')['Price'].agg(['min', 'max', 'mean'])

       min    max       mean
Type
Free  0.00    0.0   0.000000
Paid  0.99  400.0  15.297851

In [39]:
df.groupby('Type')['Rating'].agg(['min','mean','max'])

      min      mean  max
Type
Free  1.0  4.171955  5.0
Paid  1.0  4.247957  5.0

In [40]:
# Perbandingan antar grup
temp = df.groupby('Type')['Rating'].mean()
print(temp['Paid'] - temp['Free'])

0.0760027387318365

In [42]:
# Ratio
temp = df['Content Rating'].value_counts()
print(temp['Teen'] / temp['Everyone 10+'])

2.729559748427673